# fly.toml app configuration file generated for akiharuyoutube-observation on 2024-11-22T18:51:20+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'akiharuyoutube-observation'
primary_region = 'syd'

[[services]]
  internal_port = 3000
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20

  [[services.ports]]
    handlers = ["http"]
    port = "80"

  [[services.ports]]
    handlers = ["tls", "http"]
    port = "443"